### ISSUE TITLE
Multiple games with the same account in the config file.

### ISSUE THREAD

**Issue by Diyagi** [atomicptr/hoyo-daily-logins-helper#13]
Is there a way to use the same `[[Account]]` and in the `game` key specify multiple games while using a config file ?

**Comment by atomicptr** [comment]
Not quite sure what you are asking for, the same account but for multiple games?

```toml
[config]
# ...

[[accounts]]
identifier = "myhoyoaccount@gmail.com"
cookie = "...."
game = "genshin"

[[accounts]]
identifier = "myhoyoaccount@gmail.com"
cookie = "...."
game = "starrail"
```

Not sure if the cookie would be the same though
